version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./ocr_front/Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - uploads:/app/uploads
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./ocr_back/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - uploads:/app/uploads
    environment:
      - UPLOAD_FOLDER=/app/uploads
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
